ApiAuthentication/WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ApiAuthentication/WebApp/ViewModels/ForecastViewModel.cs
using SharedProject.Models;

namespace WebApp.ViewModels
{
    public class ForecastViewModel
    {
        public List<WeatherForecast>? Forecast { get; set; }
        public ResponseModel? Response { get; set; }
    }
}

ApiAuthentication/WebApp/ViewModels/LoginViewModel.cs
using SharedProject.Models;

namespace WebApp.ViewModels
{
    public class LoginViewModel
    {
        public LoginModel LoginModel { get; set; }
        public ResponseModel? Response { get; set; }
    }
}

ApiAuthentication/WebApp/ViewModels/RegisterViewModel.cs
using SharedProject.Models;

namespace WebApp.ViewModels
{
    public class RegisterViewModel
    {
        public RegisterModel RegisterModel { get; set; }
        public ResponseModel? Response { get; set; }
    }
}

ApiAuthentication/WebApp/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using SharedProject;
using SharedProject.Models;
using System.Text.Json;
using System.Text.Json.Serialization;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly string _apiUrl = "https://localhost:7120/api/";

        public AuthenticationController(IHttpClientFactory clientFactory)
        {
            _httpClientFactory = clientFactory;
        }

        [HttpGet]
        [Route("Register")]
        public async Task<IActionResult> Register()
        {
            // So far, this one can be quite basic. This method only needs to show the view to the user.
            // Could be upgraded upon in the future.

            return View(new RegisterViewModel());
        }

        [HttpGet]
        [Route("Login")]
        public async Task<IActionResult> Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        [Route("Register")]
        public async Task<IActionResult> Register(RegisterViewModel modelVM)
        {
            RegisterModel model = modelVM.RegisterModel;

            // Create the request.
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, _apiUrl + "Authentication/Register");
            request.Content = new StringContent(JsonSerializer.Serialize(model));
            request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

            // Create client and send request.
            HttpClient client = _httpClientFactory.CreateClient();
            HttpResponseMessage response = await client.SendAsync(request);

            // Handle the reply from the API.
            var responseObject = HelperMethods.Deserialize<ResponseModel>(await response.Content.ReadAsStringAsync());
            modelVM.Response = responseObject;

            return View(modelVM);
        }

        [HttpPost]
        [Route("Login")]
        public async Task<IActionResult> Login(LoginViewModel modelVM)
        {
            LoginModel model = modelVM.LoginModel;

            // Create request.
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, _apiUrl + "Authentication/Login");
            request.Content = new StringContent(JsonSerializer.Serialize(model));
            request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

            // Create client and send request.
            HttpClient client = _httpClientFactory.CreateClient();
            HttpResponseMessage response = await client.SendAsync(request);

            // Check for success and whatnot.
            if (response.IsSuccessStatusCode)
            {
                var responseFromJson = HelperMethods.Deserialize<ApiTokenLoginModel>(await response.Content.ReadAsStringAsync());
                //var responseFromJson = Deserialize<ApiTokenLoginModel>(await response.Content.ReadAsStringAsync());

                // Create a cookie so we can store the token.
                Response.Cookies.Append(
                    Constants.XAccessToken, 
                    responseFromJson.Token, 
                    new CookieOptions 
                    {
                        HttpOnly = true,
                        SameSite = SameSiteMode.Strict
                    });

                Response.Cookies.Append(
                    Constants.XAccessTokenExpiration,
                    responseFromJson.Expiration.ToString(),
                    new CookieOptions
                    {
                        HttpOnly = true,
                        SameSite = SameSiteMode.Strict
                    });

                return RedirectToAction(controllerName: "Home", actionName: "index");
            } else
            {
                var responseFromJson = HelperMethods.Deserialize<ResponseModel>(await response.Content.ReadAsStringAsync());
                modelVM.Response = responseFromJson;

                return View(modelVM);
            }
        }

        [HttpGet]
        [Route("Logout")]
        public async Task<IActionResult> Logout()
        {
            Response.Cookies.Delete(Constants.XAccessToken);
            Response.Cookies.Delete(Constants.XAccessTokenExpiration);

            return RedirectToAction(controllerName: "Home", actionName: "index");
        }
    }
}

ApiAuthentication/WebApp/Controllers/ForecastController.cs
using Microsoft.AspNetCore.Mvc;
using SharedProject;
using SharedProject.Models;
using System.Net.Http.Headers;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Route("[controller]")]
    public class ForecastController : Controller
    {
        private readonly IHttpClientFactory _clientFactory;
        private readonly string _apiUrl = "https://localhost:7120/api/";

        public ForecastController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        
        public async Task<IActionResult> Index()
        {
            var forecastVM = new ForecastViewModel();

            // Create request
            var request = new HttpRequestMessage(HttpMethod.Get, _apiUrl + "WeatherForecast");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", Request.Cookies[Constants.XAccessToken]);

            // Send
            var client = _clientFactory.CreateClient();
            var response = await client.SendAsync(request);

            // Recieve response
            if(response.IsSuccessStatusCode)
            {
                // Expect a list of weatherforecast.
                var jsonObject = HelperMethods.Deserialize<List<WeatherForecast>>(await response.Content.ReadAsStringAsync());

                forecastVM.Forecast = jsonObject;
            } else
            {
                var reasonPhrase = response.ReasonPhrase;
                var responseModel = new ResponseModel
                {
                    Status = reasonPhrase,
                    Message = (reasonPhrase == "Unauthorized") ? "You need to be logged in to access this content." : "You don't have the required permissions to access this content."
                };

                forecastVM.Response = responseModel;
            }


            return View(forecastVM);
        }
    }
}

ApiAuthentication/WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ApiAuthentication/WebApp/Views/Authentication/Login.cshtml
@model WebApp.ViewModels.LoginViewModel

<h1>Login</h1>
<form asp-action=Login asp-controller=Authentication>

    <div>
        <label asp-for=LoginModel.UserName></label>
        <input asp-for=LoginModel.UserName/>
    </div>

    <div>
        <label asp-for=LoginModel.Password></label>
        <input asp-for=LoginModel.Password/>
    </div>

    <div>
        <input type="submit" value="Login" />
    </div>

</form>

@if(Model.Response != null)
{
    <div>
        <h2>Response from API:</h2>
        <p><span>@Model.Response.Status</span> - @Model.Response.Message</p>
    </div>
}

ApiAuthentication/WebApp/Views/Authentication/Register.cshtml
@*@model SharedProject.Models.RegisterModel*@
@model WebApp.ViewModels.RegisterViewModel

<h1>Registrer en bruger.</h1>

<form asp-action=Register asp-controller=Authentication>
    <div>
        <label asp-for=RegisterModel.UserName></label>
        <input asp-for=RegisterModel.UserName />
    </div>

    <div>
        <label asp-for=RegisterModel.Password></label>
        <input asp-for=RegisterModel.Password />
    </div>

    <div>
        <label asp-for=RegisterModel.Email></label>
        <input asp-for=RegisterModel.Email />
    </div>

    <div>
        <input type="submit" value="Register" />
    </div>
</form>

@if(Model.Response != null)
{
    <div>
        <h2>Response from API:</h2>
        <p><span>@Model.Response.Status</span> - @Model.Response.Message</p>
    </div>
}

ApiAuthentication/WebApp/Views/Forecast/Index.cshtml
@model WebApp.ViewModels.ForecastViewModel


@try 
{
    @if(Model.Response != null) 
    {
        <div>
            <h1>Error! - @Model.Response.Status</h1>
            <p>@Model.Response.Message</p>
        </div>
    } else 
    {
        /* We got some data from the API, so let's show it to the user. */
        foreach(var item in Model.Forecast)
        {
            <div style="margin: 20px">
                <p>@item.Summary</p>
                <p>@item.Date - @item.TemperatureC</p>
            </div>
        }

    }
} catch(Exception ex) 
{
    <h1>@ex</h1>
}

ApiAuthentication/WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ApiAuthentication/WebApp/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor httpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forecast" asp-action="Index">Forecast</a>
                        </li>

                        @if(httpContextAccessor.HttpContext.Request.Cookies["X-Access-Token"] == null || 
                            httpContextAccessor.HttpContext.Request.Cookies["X-Access-Token-Expiration"] == null ||
                            DateTime.Parse(httpContextAccessor.HttpContext.Request.Cookies["X-Access-Token-Expiration"]) < DateTime.Now)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Register">Register</a>
                            </li>
                        } else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>